### PR TITLE
bug: proxy error 500

### LINKED ISSUE #9: Create Sample Products

### PR DESCRIPTION
**Pull request by anna-reirl**

### CODE REVIEW

**Comment by anna-reirl** [comment]
fix proxy error

**Comment by anna-reirl** [comment]
but another error in mongoose...
```
/Users/anna/Shopping-App/backend/node_modules/mongoose/lib/helpers/query/wrapThunk.js:21
      const err = new MongooseError('Query was already executed: ' + str);
                  ^

MongooseError: Query was already executed: Product.findOne({})
```

**Comment by kostia7alania** [comment]
умничка

**Comment by anna-reirl** [comment]
new error
```
const castError = new CastError();
                    ^

CastError: Cast to ObjectId failed for value "1" (type string) at path "_id" for model "Product"
```

**Pull request merged**
